import { LearningExperience } from './types.ts';

export const DEFAULT_EXPERIENCES: LearningExperience[] = [
  {
    id: 'neural-basics',
    tema: 'Redes Neuronales y Deep Learning',
    subtitulo: 'Obsidian Synthesis • De la teoría a la implementación',
    autor: '@TechConSofia',
    version: 'Deep Learning v3.2',
    createdAt: new Date().toISOString(),
    fuentes: [
      {
        id: 'f1',
        nombre: 'Guion_Neuro_v2.pdf',
        tamano: '1.4 MB',
        estado: 'Analizado',
        tipo: 'pdf',
      },
      {
        id: 'f2',
        nombre: 'Pizarra_Backprop.png',
        tamano: '840 KB',
        estado: 'OCR extraído',
        tipo: 'imagen',
      },
      {
        id: 'f3',
        nombre: 'Apuntes_Atencion.md',
        tamano: '420 KB',
        estado: 'Analizado',
        tipo: 'texto',
      },
      {
        id: 'f4',
        nombre: 'Esquema_Optimizadores.pdf',
        tamano: '2.1 MB',
        estado: 'Procesado',
        tipo: 'pdf',
      },
    ],
    stats: {
      quizViews: 428,
      cardViews: 312,
      mapViews: 189,
    },
    quiz: [
      {
        pregunta: '¿Cuál es la función principal de la «Función de Activación» en una neurona artificial?',
        opciones: [
          'Almacenar los pesos sinápticos en memoria caché.',
          'Introducir no linealidad en el modelo para aprender patrones complejos.',
          'Reducir la velocidad de procesamiento para evitar sobrecalentamiento.',
          'Eliminar neuronas inactivas automáticamente durante el entrenamiento.',
        ],
        correcta: 1,
        explicacion: 'Sin funciones de activación (como ReLU o Sigmoide), una red neuronal colapsaría matemáticamente en una regresión lineal plana, impidiendo aprender relaciones multidimensionales.',
        xp: 150,
        videoRef: {
          label: 'Ver fragmento clave en video',
          timestamp: 'min 4:15',
        },
      },
      {
        pregunta: '¿Qué problema matemático fundamental soluciona la función de activación ReLU frente a Sigmoide?',
        opciones: [
          'El desvanecimiento del gradiente (Vanishing Gradient) en capas profundas.',
          'El consumo excesivo de memoria RAM en GPU.',
          'La pérdida de precisión de punto flotante en cuantización int8.',
          'La necesidad de normalizar las imágenes de entrada a 256x256.',
        ],
        correcta: 0,
        explicacion: 'ReLU mantiene un gradiente constante de 1 para valores positivos, evitando que las derivadas sucesivas se acerquen a cero durante la retropropagación.',
        xp: 120,
        videoRef: {
          label: 'Módulo de Gradientes',
          timestamp: 'min 7:30',
        },
      },
      {
        pregunta: '¿En qué consiste el algoritmo de Retropropagación (Backpropagation)?',
        opciones: [
          'En revertir la arquitectura de la red para predecir entradas desde salidas.',
          'En calcular el gradiente de la función de pérdida respecto a cada peso aplicando la regla de la cadena.',
          'En barajar los datos de entrenamiento aleatoriamente entre épocas.',
          'En comprimir los tensores de pesos para acelerar la inferencia.',
        ],
        correcta: 1,
        explicacion: 'Backpropagation propaga el error desde la capa de salida hacia atrás, calculando derivadas parciales con la regla de la cadena para actualizar los pesos sinápticos.',
        xp: 180,
        videoRef: {
          label: 'Regla de la Cadena Visualizada',
          timestamp: 'min 12:10',
        },
      },
      {
        pregunta: '¿Qué ventaja introduce el mecanismo de «Autoatención» (Self-Attention) de los Transformers?',
        opciones: [
          'Obliga a procesar el texto palabra por palabra de forma estrictamente secuencial.',
          'Permite procesar secuencias completas en paralelo capturando dependencias a larga distancia.',
          'Elimina la necesidad de utilizar GPUs para el entrenamiento.',
          'Garantiza que el modelo nunca genere alucinaciones.',
        ],
        correcta: 1,
        explicacion: 'A diferencia de las RNNs secuenciales, Self-Attention evalúa simultáneamente las relaciones entre todas las palabras de un prompt mediante matrices Query, Key y Value.',
        xp: 200,
        videoRef: {
          label: 'Attention is All You Need',
          timestamp: 'min 18:45',
        },
      },
      {
        pregunta: '¿Cuál es el rol del optimizador Adam en el entrenamiento de redes neuronales?',
        opciones: [
          'Ajustar dinámicamente la tasa de aprendizaje (learning rate) combinando momentos y RMSprop.',
          'Elegir aleatoriamente el número de capas ocultas en cada época.',
          'Convertir automáticamente modelos de PyTorch a ONNX.',
          'Aumentar el tamaño del batch si la GPU tiene memoria libre.',
        ],
        correcta: 0,
        explicacion: 'Adam (Adaptive Moment Estimation) mantiene promedios móviles tanto de los gradientes (primer momento) como de sus cuadrados (segundo momento), acelerando la convergencia.',
        xp: 140,
      },
    ],
    flashcards: [
      {
        concepto: 'Backpropagation',
        subtitulo: 'Retropropagación del Error',
        formula: 'Δw = -η · (∂L / ∂w)',
        definicion: 'Algoritmo fundamental de optimización que calcula el gradiente de la función de pérdida con respecto a cada peso sináptico aplicando iterativamente la regla de la cadena desde la capa de salida hacia las capas iniciales.',
        ejemplo: 'Permite que la red ajuste millones de parámetros tras comparar su predicción con la etiqueta real.',
      },
      {
        concepto: 'Función de Activación',
        subtitulo: 'No-linealidad Neuronal',
        formula: 'f(z) = max(0, z)  [ReLU]',
        definicion: 'Transformación matemática aplicada a la suma ponderada de las entradas neuronales. Dota a la red de la capacidad de modelar fronteras de decisión curvas y patrones no lineales de alta dimensión.',
        ejemplo: 'Sin ella, una red de 100 capas equivaldría a una simple multiplicación lineal de matrices.',
      },
      {
        concepto: 'Transformers & Self-Attention',
        subtitulo: 'Atención Multi-Cabeza',
        formula: 'Attention(Q,K,V) = softmax(QKᵀ / √dₖ) V',
        definicion: 'Mecanismo que permite a cada token en una secuencia ponderar la relevancia de todos los demás tokens contextuales, facilitando el procesamiento masivamente paralelo y la comprensión semántica profunda.',
        ejemplo: 'Permite que la palabra "banco" entienda si habla de dinero o de un asiento según el contexto adyacente.',
      },
      {
        concepto: 'Descenso de Gradiente Estocástico (SGD)',
        subtitulo: 'Optimización por Minilotes',
        formula: 'θ_{t+1} = θ_t - η ∇L(θ_t; x_i)',
        definicion: 'Método iterativo para minimizar la función de coste evaluando gradientes sobre subconjuntos aleatorios (minilotes) en lugar de todo el conjunto de datos completo, reduciendo la carga computacional.',
        ejemplo: 'Entrena con lotes de 32 o 64 muestras en cada paso para estabilizar el aprendizaje.',
      },
      {
        concepto: 'Dropout',
        subtitulo: 'Técnica de Regularización',
        formula: 'p_{drop} ∈ [0.1, 0.5]',
        definicion: 'Técnica preventiva de sobreajuste (overfitting) que desactiva temporalmente neuronas al azar durante cada iteración de entrenamiento, obligando a la red a no depender de sinapsis aisladas.',
        ejemplo: 'Fuerza a la red a desarrollar representaciones redundantes y robustas.',
      },
    ],
    mindmap: {
      nodoPrincipal: 'Redes Neuronales',
      subnodos: [
        {
          id: 'sn-1',
          titulo: 'Arquitecturas Neuronales',
          categoria: 'Arquitectura Neuronal',
          detalles: [
            'Perceptrón Multicapa (MLP): Capas densas conectadas.',
            'Redes Convolucionales (CNN): Filtros espaciales para visión.',
            'Transformers: Mecanismo de autoatención para lenguaje.',
          ],
          videoMin: '8:20',
          quizzesCount: 3,
          tags: ['Avanzada', 'Fundamentos'],
        },
        {
          id: 'sn-2',
          titulo: 'Entrenamiento & Gradientes',
          categoria: 'Entrenamiento',
          detalles: [
            'Propagación Hacia Adelante (Forward Pass): Estimación.',
            'Cálculo de Pérdida (Cross-Entropy / MSE).',
            'Backpropagation: Regla de la cadena inversa.',
          ],
          videoMin: '12:15',
          quizzesCount: 2,
          tags: ['Matemáticas', 'Algoritmo'],
        },
        {
          id: 'sn-3',
          titulo: 'Optimización & Convergencia',
          categoria: 'Optimización',
          detalles: [
            'Adam / RMSprop: Tasa de aprendizaje adaptativa.',
            'Momentum: Inercia para escapar de mínimos locales.',
            'Programación de Learning Rate (Warmup + Cosine Decay).',
          ],
          videoMin: '6:40',
          quizzesCount: 2,
          tags: ['Hiperparámetros'],
        },
        {
          id: 'sn-4',
          titulo: 'Regularización & Generalización',
          categoria: 'Generalización',
          detalles: [
            'Dropout: Desconexión aleatoria contra sobreajuste.',
            'Batch Normalization: Estabilización de distribuciones internas.',
            'Early Stopping: Detención en punto óptimo de validación.',
          ],
          videoMin: '5:10',
          quizzesCount: 1,
          tags: ['Buenas Prácticas'],
        },
      ],
    },
  },
];
